export const GET_RECIPES = 'GET_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const SEARCH_RECIPE_BY_NAME = 'SEARCH_RECIPE_BY_NAME';
export const SEARCH_RECIPE_BY_TAG = 'SEARCH_RECIPE_BY_TAG';
